### ISSUE TITLE
Fails to compile on Raspberry-Pi Flavor Linux

### ISSUE THREAD

**Issue by alexkrob** [EstebanBorai/local-ip-address#10]
The bit of code that's in this `unsafe` block right here:
https://github.com/EstebanBorai/local-ip-address/blob/95f613daa20d8d5760fbd5624051e89c9e675a48/src/linux.rs#L200

should read
```rust
let len = strlen(str as *const u8);
```

in order to successfully compile on Linux.

**Comment by EstebanBorai** [comment]
Thanks for the support to this crate @alexkrob !
Let's keep all the conversation in the PR you already made, see you there!
