### ISSUE TITLE
Compilation error  with version local-ip-address-0.5.2 

### ISSUE THREAD

**Issue by mokeyish** [EstebanBorai/local-ip-address#107]
![图片](https://user-images.githubusercontent.com/16131917/222942558-2aeb549f-8f95-4540-9715-39c58633e824.png)

![图片](https://user-images.githubusercontent.com/16131917/222942051-b315c8f5-a4a3-4cb1-9a19-afc5326843d8.png)

https://github.com/mokeyish/smartdns-rs/actions/runs/4334200756/jobs/7567928721

**Comment by mokeyish** [comment]
BTW, Compilation error also occus with android(Termux).

**Comment by EstebanBorai** [comment]
Hi @cgzones! I think this is related to your latest contribution, perheps this may affect somewhere where you are using this crate?

**Comment by mokeyish** [comment]
> Hi @mokeyish! Thanks for opening this issue!
> 
> Looks related to last update, can you help me providing how are you trying to compile your project? So I can take it into account for testing?

Thanks for your reply, I compile my project by github action. Add the [CI file](https://github.com/mokeyish/smartdns-rs/blob/main/.github/workflows/release.yml) to this project for testing?

**Comment by EstebanBorai** [comment]
Hi @mokeyish, @cgzones I just yanked version `0.5.2` due to the fact that some issues have raised since its release.
I recommend using `0.5.1` instead while fixes are published.

Sorry about the inconveniences 🙏🏻!

**Comment by EstebanBorai** [comment]
Hi @mokeyish! I just released `0.5.3` can you see how it works for you now?
@cgzones introduced recent changes that might help:

- https://github.com/EstebanBorai/local-ip-address/pull/121
- https://github.com/EstebanBorai/local-ip-address/pull/105
- https://github.com/EstebanBorai/local-ip-address/pull/108

Kudos to @cgzones! 🎉

**Comment by mokeyish** [comment]
Thanks! with the version `0.5.3`, this issue has been solved. It passed all checks.
https://github.com/mokeyish/smartdns-rs/pull/128/checks
