### ISSUE TITLE
New release for windows-sys 0.48

### ISSUE THREAD

**Issue by nox** [EstebanBorai/local-ip-address#118]
Can we get a new release? I'm attempting to deduplicating windows-sys in a work project.

**Comment by EstebanBorai** [comment]
Hi @nox! Sounds good to me!
Do you feel like opening a PR? I would be glad to review, merge and publish later today!

**Comment by nox** [comment]
Ah, windows-sys 0.49 was released last week hah.

**Comment by EstebanBorai** [comment]
Hi @nox latest version of `local-ip-address@0.5.3` now uses `windows-sys@0.48`!

https://github.com/EstebanBorai/local-ip-address/blob/main/Cargo.toml#L26-L34
