### ISSUE TITLE
Cannot compile for Windows MSVC on Linux

### ISSUE THREAD

**Issue by msenol86** [EstebanBorai/local-ip-address#28]
When I try to compile via `cargo build --target x86_64-pc-windows-msvc` I get this error. Other crates compiled successfully.
```
 --> /home/msenol/.cargo/registry/src/github.com-1ecc6299db9ec823/local-ip-address-0.4.4/src/windows.rs:2:5
  |
2 |     windows::include_bindings!();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `::std::include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `local-ip-address`


```

**Comment by EstebanBorai** [comment]
Hi @msenol86!
Just to be clear, you are trying to compile this crate on Linux targeting Windows, am I right?

**Comment by EstebanBorai** [comment]
I'm missing the error message in your output copy, but reviewing the command you executed and given that you mention that your host system is Linux, I can tell that you are having the same issue as here: https://github.com/EstebanBorai/local-ip-address/issues/16

As I mentioned in such issue:

> The crate used to interact with Windows Win32 API is https://github.com/microsoft/windows-rs, this issue is already being tracked by the contributors of such crate here: microsoft/windows-rs#638

A workaround to this is to have builds made on VMs or taking advantage of your CI workflow as it's being done with this crate here:

https://github.com/EstebanBorai/local-ip-address/blob/7bc03c2b3398e0d039344345364d71618ea3fe26/.github/workflows/build.yml#L17

You could then use the artifacts generated by your workflow.

**Comment by EstebanBorai** [comment]
@msenol86 , hope you are doing great!

Any thoughts on this? Were you able to give a try on my suggestion?

**Comment by msenol86** [comment]
> Hi @msenol86! Just to be clear, you are trying to compile this crate on Linux targeting Windows, am I right?

Yes sorry my bad.

**Comment by EstebanBorai** [comment]
Thanks for replying @msenol86, have a nice weekend!
