### ISSUE TITLE
Incorrect local IP address got on Windows 

### ISSUE THREAD

**Issue by machengim** [EstebanBorai/local-ip-address#31]
Running test functions on Windows 10 on a NUC8 machine got incorrect local IP address as follows (the `ifas` value is also printed out):

```
ifas is [("Ethernet", fe80::5968:d94e:958e:1e5c), ("Ethernet", 169.254.30.92), 
("VirtualBox Host-Only Network", fe80::a095:abb9:e1b9:5bd6), ("VirtualBox Host-Only Network", 192.168.56.1),
 ..., 
("Wi-Fi", fe80::1d7e:8c98:843:b568), ("Wi-Fi", 192.168.0.13), 
("Bluetooth Network Connection", fe80::585e:ad7:2517:b448), ("Bluetooth Network Connection", 169.254.180.72), 
("Loopback Pseudo-Interface 1", ::1), ("Loopback Pseudo-Interface 1", 127.0.0.1)]

test tests::find_network_interfaces ... Windows 'local_ip': 169.254.30.92
ok
test tests::find_local_ip ... ok
```

Seems like `Wi-fi` should be used in this case, but not sure if it's a common issue.

**Comment by EstebanBorai** [comment]
Hi @machengim! Thanks for reporting!

This error is being tracked already, a better definition to have an universal approach for retrieving local IP address for Windows is being developed.

I will keep you updated.

A workaround for now is to handle this by checking on the desired network name.

This is a similar issue:
https://github.com/EstebanBorai/local-ip-address/issues/18

Thanks again!

**Comment by EstebanBorai** [comment]
@skandabhairava thanks for reporting this issue!

This needs a review clearly, if you want to work on it just let me know! I will be checking it and get back to you when I have some insights or a fix!

**Comment by EstebanBorai** [comment]
Fixed on https://github.com/EstebanBorai/local-ip-address/pull/79
