### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by nashley** [EstebanBorai/local-ip-address#74]
A [number of dependencies](https://github.com/EstebanBorai/local-ip-address/compare/v0.4.4...main) have been updated since `v0.4.4`.
Could a new patch release be made so newer versions of these dependencies can be used?

**Comment by EstebanBorai** [comment]
Totally right! Thanks for pointing it out and sorry about it! Will release ASAP!

**Comment by EstebanBorai** [comment]
@nashley im fixing things up, making sure all CI workflows run but I encountered an issue with the latest `windows` version in the following CI workflow: https://github.com/EstebanBorai/local-ip-address/runs/7313358601?check_suite_focus=true.

Will take a bit more of time. If you want to take a chance on it great!

**Comment by nashley** [comment]
Looks like some code is now behind a new feature (`Win32_NetworkManagement_Ndis`) as of [this commit](https://github.com/microsoft/windows-rs/pull/1783/files#diff-d1ab09ce83262d4c9e199e263119084ebf1cad945d2856b4fc964e4ecf1de0beR132).
For some reason, I can't find documentation for this online, but I guess that's Microsoft for ya.

I made a simple PR: https://github.com/EstebanBorai/local-ip-address/pull/75

Thanks for getting back so quickly!

**Comment by EstebanBorai** [comment]
Thanks so much @nashley! I had run the CI workflows and there's an issue with the Windows test, lets followup there!

**Comment by EstebanBorai** [comment]
@nashley a new release is available here: https://github.com/EstebanBorai/local-ip-address/releases/tag/v0.4.5.

There's clearly issues with Windows (you can see other issues listed in the issues section), if you want to help fixing them count on me for any support I can give to you!

Happy coding!

**Comment by nashley** [comment]
Thank you!
