### ISSUE TITLE
Use `std::alloc::alloc` instead of `libc::malloc`

### ISSUE THREAD

**Issue by MaderNoob** [EstebanBorai/local-ip-address#80]
The `libc::malloc` implementation doesn't respect the required alignment of different data types, and on machines where `malloc` returns addresses that are not aligned enough, this might cause undefined behaviour.

Is there a specific reason why `libc::malloc` is used instead of the standard library's implementation?

**Comment by EstebanBorai** [comment]
Hi @MaderNoob!

Thanks for opening this issue and taking the time to improve this crate.
You are right, we should be using `alloc` from the `std` library instead. I'm already working on a PR (#81) based on your request/recommendation.

Feel free to provide some input there!

Thanks again.

**Comment by EstebanBorai** [comment]
As I can see in CI workflows as well as for my local development system, changes work as expected.
I will land a new version soon.

Thanks again @MaderNoob!
