### ISSUE TITLE
MacOS bug on 0.5.0

### ISSUE THREAD

**Issue by newdev8** [EstebanBorai/local-ip-address#97]
When using it on 0.4.9 it works perfectly fine, but when updating to 0.5.0 I get `127.0.0.1` on MacOS. Still works on Linux and Windows.

_MacBook Pro running MacOS Ventura._

**Comment by EstebanBorai** [comment]
Interesting! Thanks for reporting @newdev8!
I will review it and get back to you!

**Comment by EstebanBorai** [comment]
@jakewilliami I think we could reintroduce `macOS` specific approach and use https://github.com/EstebanBorai/local-ip-address/blob/main/src/bsd.rs only for BSD based instead.

Having a dedicated macOS looks like a better approach.

**Comment by EstebanBorai** [comment]
@newdev8 I just did a draft here: https://github.com/EstebanBorai/local-ip-address/pull/98 reintroducing macOS impl.
Can you tell me if it works for you please?

**Comment by newdev8** [comment]
@EstebanBorai thanks for your quick reply!

I've tested it and works like a charm 🍀.

**Comment by jakewilliami** [comment]
@newdev8 thank you for raising this.  @EstebanBorai, nice, quick fix.  Curious that [v0.5](https://github.com/EstebanBorai/local-ip-address/tree/v0.5.0) introduced a bug, as we wrote [specific logic](https://github.com/EstebanBorai/local-ip-address/blob/v0.5.0/src/bsd.rs#L139-L144) to handle this case.  I'll look into it, as macOS should not require a separate solution, I think.

**Comment by jakewilliami** [comment]
Oh dear, I think [this](https://github.com/EstebanBorai/local-ip-address/blob/v0.5.0/src/lib.rs#L128-L132) is the logical mistake—this is the exact opposite filter we want!  I inverted this and it works now on my macOS machine.

Before:
<img width="1043" alt="Screen Shot 2023-01-05 at 7 43 54 PM" src="https://user-images.githubusercontent.com/54291317/210718143-590c33cc-dc0e-4c22-83ad-2e372affd264.png">

After:
<img width="1039" alt="Screen Shot 2023-01-05 at 7 45 18 PM" src="https://user-images.githubusercontent.com/54291317/210718334-8f6a7527-d285-476a-9d57-a69835baba1c.png">

Diff:
<img width="728" alt="Screen Shot 2023-01-05 at 7 45 45 PM" src="https://user-images.githubusercontent.com/54291317/210718389-f851c851-b567-4228-ab62-c5db45e773b2.png">

---

Obviously it's difficult to catch these "semantic" errors, as we can't test for exact local IP in our unit tests, unless we cross check it with `ip -a` or something like that.  I wonder how we can avoid these errors in future.  Thank you again @newdev8 for bringing this to our attention!
